services:
  bookmarket:
    image: bookmarket:latest
    container_name: bookmarket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache
    env_file:
      - .env  # ✅ 환경 변수 파일 등록
    networks:
      - backend

  # mysql-db:
  #   image: mysql:8.0
  #   container_name: mysql-db
  #   environment:
  #     MYSQL_DATABASE: bookmarket
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - backend

  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - backend


networks:
  backend:
    driver: bridge
